defaults:
  - _aucurriculum_train_
  - _self_

results_dir: /mimer/NOBACKUP/groups/ulio_inverse/zhiping/data
experiment_id: Gaussian_20dB_anticurriculum
iterations: 15

train_augmentation:
  _target_: autrainer.augmentations.AugmentationPipeline
  id: SNR_noise(20dB)
  generator_seed: 0
  pipeline:
    - autrainer.augmentations.SNR_noise:
        snr: 20
        noise_type: StaticGaussian
        p: 1.0
        generator_seed: 0

hydra:
  sweeper:
    params:
      +seed: 1
      +batch_size: 64
      +learning_rate: 0.001
      dataset: SpeechCommands-16k
      model: Cnn10
      optimizer: Adam
      curriculum: AntiCurriculum
      curriculum/sampling: Original
      curriculum/scoring: CumulativeAccuracy
      curriculum/pacing: Logarithmic
      curriculum.pacing.initial_size: 0.2
      curriculum.pacing.final_iteration: 0.5
